include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

variables:
  TAG: "1.0"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "${IMAGE_REPOSITORY}"

stages:
  - read-secret
  - docker-build

read_secret:
  only:
    - web
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build:
  needs: ["read_secret"]
  only:
    - web
  variables:
    WORKING_DIR: "."
    IMAGE_NAME: pong
  stage: docker-build
  extends:
    - .kaniko:simple-build-push